#!/bin/sh

set -e

RELEASE=$(config-manager update release)
case "$RELEASE" in
    nightly)
        FW_URL="https://github.com/FenrixiR/cosmos-nebula/releases/download/nightly/cosmos-nebula-upgrade-elegoo-centauri-carbon1.swu"
        ;;
    *)
        FW_URL="https://github.com/FenrixiR/cosmos-nebula/releases/latest/download/cosmos-nebula-upgrade-elegoo-centauri-carbon1.swu"
        ;;
esac

SWUFILE="/user-resource/update.swu"

# Download firmware
curl -k -f -S -o "$SWUFILE" -L "$FW_URL"

# Install firmware
flash "$SWUFILE"

# Clean up firmware file
rm "$SWUFILE"

reboot
